experiment:
  app: poisson
  estimand: group_rates_weighted_sum
  model: naive_group_rates
  id: ~
  sim_id: ~
  iter_id: ~
  description: >
    Estimate a separate Poisson rate (θ_j) for each group using observed counts 
    and known exposure times. No covariates or regression structure; each group 
    is treated independently. Group-level weights can vary and influence summaries 
    (e.g., weighted averages).

seed: 2685

groups:
  n_groups: 50
  n_per_group: 3              # Single number applies to all groups
  labels: auto_upper           # Options: auto_upper, auto_lower, auto_num, or explicit list

theta:
  distribution: runif         # Options: uniform, normal, lognormal, fixed
  args: [1.0, 5.0]              # If uniform → min, max
  per_group: true               # If true → draw per group; if false → one value applied to all

exposure:
  name: t
  distribution: runif
  args: [1, 3]                  # t_i ~ U(1, 3)

weights:
  distribution: runif
  args: [1, 10]
  normalize_mean_to: 1.0
