experiment:
  app: poisson
  estimand: group_rates_weighted_sum
  model: fixed_effects_regression_with_common_slopes
  id: ~
  sim_id: ~
  iter_id: ~
  description: >
    Estimate group-specific Poisson rates within a fixed-effects regression that includes covariates.
    Observed counts are modeled with known exposure times (offsets), categorical indicators for groups,
    and additional covariates. Group effects are estimated jointly with common covariate effects (shared slopes).
    Group-level weights can vary and are applied when forming summaries (e.g., weighted sums or averages
    of estimated rates). Rates can be evaluated at particular covariate values (e.g., reference values
    or sample means) or integrated/marginalized over a covariate distribution.

seed: 6481

model:
  groups:
    n_groups: 5
    n_per_group:
      mode: fixed                  # options: fixed, sample
      args: 3                      # if fixed → single integer; if sample → [min, max] or distribution spec
    labels: auto_upper             # Options: auto_upper, auto_lower, auto_num, or explicit list

  covariates:
    - name: X1
      type: continuous
      distribution: rnorm
      args: [0, 1]                
    - name: X2
      type: continuous
      distribution: runif
      args: [-3, 3]                 
    - name: X3
      type: continuous
      distribution: rt
      args: [5, 0]                 

  true_params:
    Beta_0:
      # Each element will be a vector: intercept + coefficients
      intercepts:
        distribution: runif
        args: [1.0, 5.0]
        scale: rate                # Options: "log" (draw log-rate) or "rate" (draw theta directly)
      coefficients:
        # mode: fixed            
        # args: [0.2, -0.1]        
        mode: sample
        distribution: runif
        args: [-1.0, 1.0]
        
exposure:
  name: t
  distribution: runif
  args: [2, 5]                    # t_i ~ U(1, 3)

weights:
  distribution: runif             # alpha_g ~ U(1, 10)
  args: [1, 10]
  normalize_mean_to: 1.0

evaluation:
  mode: reference                 # options: reference, marginal
  reference:
    xstar:
      X1: 0.0
      X2: 0.0
      X3: 0.0
  marginal:
    over: sample                  # options: sample (use simulated X), group (average within group)
    summary: mean
