IL:
  step_size: 0.05
  fine_step_size: 0.025
  fine_window: 0.1
  num_std_errors: [-2.5, 6.0]
  chunk_size: 4
PL: 
  step_size: 0.05
  fine_step_size: 0.025
  fine_window: 0.1
  alpha_levels: [0.1, 0.05, 0.01]

