experiment:
  app: poisson_regression
  estimand: weighted_sum
  id: ~
  sim_id: ~
  iter_id: ~

seed: 2685

group_structure:
  pooled: FALSE
  n_groups: 5
  n_per_group: 50

group_covariates:
  intercept: true
  covariates:
    - name: X1
      distribution: rnorm
      args: [0, 1]
    - name: X2
      distribution: runif
      args: [-2, 2]
    - name: X3
      distribution: rbinom
      args: [1, 0.4]

beta:
  distribution: rnorm
  args: [0, 1]

exposure:
  name: t
  distribution: runif
  args: [1, 3]  # Example: exposure time between 1 and 3 units per observation

weights:
  level: group
  distribution: runif
  args: [1, 10]
  normalize_mean_to: 1.0  # or normalize_sum_to: 100
