experiment:
  app: multinomial_logistic_regression
  estimand: shared_effect
  id: ~
  sim_id: ~
  iter_id: ~

data_generation:
  seed: 6349
  n_obs: 150
  validate_only: false
  min_obs: 5
  max_tries: 100

model:
  response:
    name: "Y"
    num_classes: 7
    reference_class: 7
  
  intercepts:
    distribution: rnorm
    parameters:
      mean: 0
      sd: 0.5

  predictors:
    shared:
        name: Z
        effect: 0.5
        observations:
          distribution: rnorm
          parameters:
            mean: 0
            sd: 2

    class_specific:
      - name: X1
        effects:
          distribution: rnorm
          parameters:
            mean: 0.5
            sd: 0.1
        observations:
          distribution: rnorm
          parameters:
            mean: 0
            sd: 1

      - name: X2
        effects:
          distribution: rnorm
          parameters:
            mean: -0.5
            sd: 1
        observations:
          distribution: runif
          parameters:
            min: -2
            max: 2

      - name: X3
        effects:
          distribution: rnorm
          parameters:
            mean: 1
            sd: 2
        observations:
          distribution: rnorm
          parameters:
            mean: 0
            sd: 1.5

      - name: X4
        effects:
          distribution: rnorm
          parameters:
            mean: -1
            sd: 1
        observations:
          distribution: rnorm
          parameters:
            mean: 0
            sd: 1

      - name: X5
        effects:
          distribution: rnorm
          parameters:
            mean: 0
            sd: 1
        observations:
          distribution: rnorm
          parameters:
            mean: 0
            sd: 1

  formula: "Y ~ Z + X1 + X2 + X3 + X4 + X5"

