experiment:
  app: poisson
  estimand: group_rates_weighted_sum
  model: fixed_effects_varying_slope
  id: ~
  sim_id: ~
  iter_id: ~
  description: >
    Estimate group-specific Poisson rates within a fixed-effects regression with covariates.
    Observed counts are modeled with known exposure times (offsets), categorical indicators for groups,
    and additional covariates. Each group has its own intercept and slope for at least one covariate,
    while other covariate effects can be shared across groups. Group-level weights are applied when
    forming summaries such as weighted sums or averages of estimated rates. Group rates can be evaluated
    at particular covariate values (reference values) or marginalized over a covariate distribution.

model:
  
  seed: 1762

  groups:
    n_groups: 3
    n_per_group:
      mode: fixed                  # options: fixed, sample
      args: 3                      # if fixed → single integer; if sample → [min, max] or distribution spec
    labels: auto_upper             # Options: auto_upper, auto_lower, auto_num, or explicit list
    
  intercepts:
    common:
      symbol: κ
      distribution:
        name: rnorm
        args: [0.0, 1.0]
    group_deviation:
      symbol: δ
      distribution: 
        name: rnorm
        args: [0.0, 0.2]

  covariates:
    - name: X1
      distribution:
        name: runif
        args: [-1.0, 1.0]
      slope:
        baseline:
          symbol: ρ
          distribution: 
            name: rnorm
            args: [0.2, 0.05]
        group_deviation: null    # shared slope across groups
  
    - name: X2
      distribution:
        name: rnorm
        args: [0.0, 1.0]
      slope:
        baseline:
          symbol: γ
          distribution: 
            name: rnorm
            args: [0.5, 0.1]
        group_deviation:
          symbol: ζ
          distribution:
            name: rnorm
            args: [0.0, 0.05]

  exposure:
    symbol: t
    distribution: 
      name: runif
      args: [2, 4]                     # t_i ~ Uniform(2,4)

  weights:
    symbol: α
    distribution: 
      name: runif               # weights for group-level summaries
      args: [1, 10]
    normalize_mean_to: 1.0

  evaluation:
    mode: marginal                  # options: reference, marginal
    reference:
      xstar:
        X1: 0.0
        X2: 0.0
    marginal:
      over: sample                   # options: sample (use simulated X), group (average within group)
      summary: mean
