experiment:
  app: negative_binomial
  estimand: process_rates_weighted_sum
  model: naive_rates
  id: exp_v7.0.1
  sim_id: ~
  iter_id: ~
  description: |
    Estimate a separate rate (Î¸_j) for each negative binomial process using observed counts and known exposure times. No covariates or regression structure; each process  is treated independently. Process-level weights can vary and influence summaries  (e.g., weighted averages).
seed: 9406
processes:
  n_processes: 5
  n_per_process: 10
  labels: auto_upper
theta:
  distribution: runif
  args:
  - 1.0
  - 5.0
  per_process: true
phi:
  distribution: rgamma
  args:
  - 5.0
  - 2.0
  per_process: true
exposure:
  name: t
  distribution: runif
  args:
  - 1
  - 3
weights:
  distribution: runif
  args:
  - 1
  - 10
  normalize_mean_to: 1.0

