experiment:
  app: poisson
  estimand: group_rates_weighted_sum
  model: naive_group_rates
  id: exp_v3.0.1
  sim_id: ~
  iter_id: ~
  description: |
    Estimate a separate Poisson rate (Î¸_j) for each group using observed counts  and known exposure times. No covariates or regression structure; each group  is treated independently. Group-level weights can vary and influence summaries  (e.g., weighted averages).
seed: 2685
groups:
  n_groups: 50
  n_per_group: 3
  labels: auto_upper
theta:
  distribution: runif
  args:
  - 1.0
  - 5.0
  per_group: true
exposure:
  name: t
  distribution: runif
  args:
  - 1
  - 3
weights:
  distribution: runif
  args:
  - 1
  - 10
  normalize_mean_to: 1.0

