experiment:
  app: multinomial_logistic_regression
  estimand: shared_effect
  id: exp_v2.0.0
  sim_id: ~
  iter_id: ~
data_generation:
  seed: 5387
  n_obs: 500
  validate_only: false
model:
  response:
    name: true
    num_classes: 6
    reference_class: 6
    num_effects: 5
  predictors:
    shared:
      name: Z
      effect: 1.2
      distribution:
        type: normal
        parameters:
          mean: 0
          sd: 1
    class_specific:
    - name: X1
      effects:
      - 1.0
      - -1.0
      - 0.5
      - 0.5
      - 0.0
      distribution:
        type: normal
        parameters:
          mean: 0
          sd: 1
    - name: X2
      effects:
      - 0.5
      - 0.5
      - -0.5
      - 0.0
      - 0.3
      distribution:
        type: normal
        parameters:
          mean: 0
          sd: 1
  intercepts:
  - 0.5
  - -0.5
  - 0.2
  - -0.1
  - 0.0
  interactions: []

